{{- if .Values.tetragon.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- with .Values.daemonSetAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
  {{- with .Values.daemonSetLabelsOverride}}
    {{- toYaml . | nindent 4 }}
  {{- else }}
    {{- include "tetragon.labels" . | nindent 4 }}
  {{- end }}
  name: {{ include "tetragon.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
    {{- with .Values.selectorLabelsOverride }}
      {{- toYaml . | nindent 6 }}
    {{- else }}
      {{- include "tetragon.selectorLabels" . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ toJson .Values.tetragon | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.podLabelsOverride }}
        {{- toYaml . | nindent 8 }}
      {{- else }}
        {{- include "tetragon.labels" . | nindent 8 }}
      {{- end }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: "{{ . }}"
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tetragon.serviceAccount" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- include "initcontainers.extra" . | nindent 6 }}
      containers:
{{- if eq .Values.export.mode "stdout" }}
      {{- include "container.export.stdout" . | nindent 6 -}}
{{- end }}
      {{- include "container.tetragon" . | nindent 6 -}}
      {{- include "containers.extra" . | nindent 6 -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      terminationGracePeriodSeconds: 1
      volumes:
      - name: cilium-run
        hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
      - name: export-logs
        hostPath:
          path: {{ .Values.exportDirectory }}
          type: DirectoryOrCreate
      - name: tetragon-config
        configMap:
          name: {{ include "tetragon.configMapName" . }}
      - name: bpf-maps
        hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
      - name: host-proc
        hostPath:
          path: {{ .Values.tetragon.hostProcPath }}
          type: Directory
{{- if and (.Values.tetragon.cri.enabled) (.Values.tetragon.cri.socketHostPath) }}
      - name: cri-socket
        hostPath:
          path: {{ quote .Values.tetragon.cri.socketHostPath }}
          type: Socket
{{- end }}
      {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
{{- range .Values.extraHostPathMounts }}
      - name: {{ .name }}
        hostPath:
          path: {{ .mountPath }}
{{- end }}
      {{- include "volumes.extra" . | nindent 6 }}
{{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
