baseURL = "/"
title = "Tetragon - eBPF-based Security Observability and Runtime Enforcement"
description = "Tetragon is a low overhead, flexible, and Kubernetes native security observability tool that applies policy and filtering directly in the kernel using eBPF"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Comment out to enable taxonomies in Docsy
disableKinds = ["taxonomy"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

# Language configuration
[languages]
[languages.en]
languageName ="English"
weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "monokailight"

[[menu.main]]
    name = "Documentation"
    weight = 10
    url = "/docs"

[[menu.main]]
    name = "Community"
    weight = 20
    url = "https://cilium.io/get-involved/"

[[menu.main]]
    name = "Getting Started"
    weight = 30
    url = "/docs/getting-started"

[[menu.main]]
    name = "Enterprise"
    weight = 40
    url = "/enterprise"

[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/cilium/tetragon/"
    pre = "<i class=\"fa-brands fa-github\"></i>"


#######################################
# Everything below this are Site Params
#######################################

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print", "RSS"]

[params]
copyright = "The Authors of Tetragon"
# privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
images = ["default-twitter-card-image.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# [[params.versions]]
# fullversion = "v1.26.0"
# version = "v1.26"
# githubbranch = "v1.26.0"
# docsbranch = "main"
# url = "https://kubernetes.io"
#
# [[params.versions]]
# fullversion = "v1.25.5"
# version = "v1.25"
# githubbranch = "v1.25.5"
# docsbranch = "release-1.25"
# url = "https://v1-25.docs.kubernetes.io"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/cilium/tetragon"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/cilium/tetragon"

# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "docs"

# URL of the Star Wars demo app.
demo_app_url = "https://raw.githubusercontent.com/cilium/cilium/v1.15.3/examples/minikube/http-sw-app.yaml"

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
# renovate: datasource=docker depName=quay.io/cilium/tetragon
version = "v1.4.0"

[params.search.algolia]
appId = "UI18HE156K"
apiKey = "77f164b3638095772b770596db900fea"
indexName = "tetragon"

# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = true
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set a desired menu depth always visible
ul_show = 1
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

[params.links]
[[params.links.developer]]
  name = "GitHub"
  url = "https://github.com/cilium/tetragon"
  icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
  name = "Slack"
  url = "https://slack.cilium.io"
  icon = "fab fa-slack"
  desc = "Chat with other project developers"

# Modify default caches to cacheDir all the time instead of resources because
# of permissions issues in default local resources directory. See following:
# - https://gohugo.io/getting-started/configuration/#configure-file-caches
# - https://github.com/kubernetes/website/pull/24475/files#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77
[caches]
  [caches.assets]
    dir = ":cacheDir/_gen"
    maxAge = -1
  [caches.images]
    dir = ":cacheDir/_images"
    maxAge = -1

#######################################
# hugo module configuration
#######################################

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
