---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.5
  name: podinfo.cilium.io
spec:
  group: cilium.io
  names:
    kind: PodInfo
    listKind: PodInfoList
    plural: podinfo
    shortNames:
    - tgpi
    singular: podinfo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: PodInfo is the Scheme for the Podinfo API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              hostNetwork:
                description: |-
                  Host networking requested for this pod. Use the host's network namespace.
                  If this option is set, the ports that will be used must be specified.
                type: boolean
              nodeName:
                description: NodeName is the name of the node that the pod is schduled
                  to run on.
                type: string
            type: object
          status:
            properties:
              podIP:
                description: |-
                  IP address allocated to the pod. Routable at least within the cluster.
                  Empty if not yet allocated.
                type: string
              podIPs:
                description: List of Ip addresses allocated to the pod. 0th entry
                  must be same as PodIP.
                items:
                  properties:
                    IP:
                      description: IP is an IP address (IPv4 or IPv6) assigned to
                        the pod
                      type: string
                  type: object
                type: array
            type: object
          workloadObject:
            description: Workload that created this pod.
            properties:
              name:
                description: Name of the object.
                type: string
              namespace:
                description: Namespace of this object.
                type: string
            type: object
          workloadType:
            description: Workload type (e.g. "Deployment", "Daemonset") that created
              this pod.
            properties:
              apiVersion:
                description: |-
                  APIVersion defines the versioned schema of this representation of an object.
                  Servers should convert recognized schemas to the latest internal value, and
                  may reject unrecognized values.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
                type: string
              kind:
                description: |-
                  Kind is a string value representing the REST resource this object represents.
                  Servers may infer this from the endpoint the client submits requests to.
                  Cannot be updated.
                  In CamelCase.
                  More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
                type: string
            type: object
        type: object
    served: true
    storage: true
