{{- if and .Values.serviceAccount.create .Values.podWatcher.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-operator-service-account
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tetragon-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
