{{- if .Values.tetragon.prometheus.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- with .Values.serviceLabelsOverride}}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    {{- include "tetragon.labels" . | nindent 4 }}
    {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: metrics
      port: 2112
      protocol: TCP
      targetPort: {{ .Values.tetragon.prometheus.port }}
  selector:
    {{- with .Values.daemonSetLabelsOverride}}
    {{- toYaml . | nindent 4 }}
    {{- else }}
    {{- include "tetragon.labels" . | nindent 4 }}
    {{- end }}
  type: ClusterIP
{{- end }}
