name: Validate that generated files are up to date
on:
  push:
    branches:
      - main
      - v*
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  generated-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: '1.22.9'
      - name: Go version
        run: go version
      - name: Validate that generated files are up to date.
        run: |
          make generate
          make codegen
          git status
          git diff
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status --porcelain
            echo "Please run 'make generate && make codegen' and submit your changes."; exit 1
          fi
      - name: Check Tetragon daemon flags
        run: |
          make generate-flags
          git status
          git diff
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status --porcelain
            echo "Please run 'make generate-flags' and submit your changes'"; exit 1
          fi
      - name: Check metrics docs
        run: |
          make lint-metrics-md
