name: Check generated docs
on:
  push:
    branches:
      - main
      - v*
    paths:
      - "**"
      - "!docs/**"
      - "!examples/**"
      - "!install/**"
      - "!tests/**"
      - "!**.md"
      - "!**.yaml"
      - docs/content/en/docs/reference/metrics.md
      - docs/data/tetragon_flags.yaml
      - docs/content/en/docs/reference/templates/tracing_policy.tmpl
      - .github/workflows/generated-docs.yaml
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "!examples/**"
      - "!install/**"
      - "!tests/**"
      - "!**.md"
      - "!**.yaml"
      - docs/content/en/docs/reference/metrics.md
      - docs/data/tetragon_flags.yaml
      - docs/content/en/docs/reference/templates/tracing_policy.tmpl
      - .github/workflows/generated-docs.yaml

jobs:
  check-generated-docs:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: "1.25.5"
      - name: Go version
        run: go version
      - name: Check Tetragon daemon flags
        run: |
          set -ex
          make generate-flags
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status
            git diff
            echo "Generated flags reference is outdated."
            echo "Please run 'make generate-flags' and submit your changes."; exit 1
          fi
      - name: Check metrics docs
        run: |
          set -ex
          make metrics-docs
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status
            git diff
            echo "Generated metrics reference is outdated."
            echo "Please run 'make metrics-docs' and submit your changes."; exit 1
          fi
      - name: Check tracing policy docs
        run: |
          set -ex
          make tracing-policy-docs
          test -z "$(git status --porcelain)"
          if [ $? != 0 ]; then
            git status
            git diff
            echo "Generated tracing policy reference is outdated."
            echo "Please run 'make tracing-policy-docs' and submit your changes."; exit 1
          fi
