name: tetragon-rthooks test
on:
  pull_request:
    paths:
      - 'contrib/tetragon-rthooks/**'
  push:
    branches:
      - main
    paths:
      - 'contrib/tetragon-rthooks/**'

jobs:
  build:
    name: Build tetragon-rthooks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.ref }}-rthooks-build
      cancel-in-progress: true
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        path: go/src/github.com/cilium/tetragon/

    - name: Install Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.25.5'

    - name: Build
      env:
        GOPATH: /home/runner/work/tetragon/tetragon/go
      run: |
        cd go/src/github.com/cilium/tetragon/contrib/tetragon-rthooks
        make

    - name: tar build
      run: |
        cd go/src/github.com/cilium/tetragon/contrib
        tar cz -f /tmp/tetragon-rthooks.tar ./tetragon-rthooks

    - name: upload build
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
         name: tetragon-rthooks-build
         path: /tmp/tetragon-rthooks.tar
         retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
        fail-fast: false
        matrix:
           cri:
            - "containerd"
            - "crio"
    concurrency:
      group: ${{ github.ref }}-rthooks-test-${{ matrix.cri }}
      cancel-in-progress: true
    steps:
    - name: start minikube
      uses: medyagh/setup-minikube@e3c7f79eb1e997eabccc536a6cf318a2b0fe19d9 # v0.0.20
      with:
        driver: docker
        container-runtime: ${{ matrix.cri }}

    - name: download build data
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
         name: tetragon-rthooks-build

    - name: extract build data
      run: |
        tar xf tetragon-rthooks.tar

    - name: run test
      run: |
        cd tetragon-rthooks
        ./scripts/minikube-install-hook.sh -l
        ./scripts/minikube-test-hook.sh
